%% Wrapper for generating input data

%general path to load data files fromk
matdir = '/Users/christophermezias/Documents/MISS-MatFiles';

%% Input data from Tasic, et al., 2018 & Lein, et al., 2007, AIBS
load([matdir filesep 'Tasic_Inputs.mat'],'GENGDmod','listBmap',...
    'nonzerovox','structIndex','structList','voxvgene');

classstruct = scRNAseq_Data_Extract_Tasic(matdir);
[genevct, genevct_subt, classkey, classkey_subt, ...
    C_indivcells, ct_labvec, subt_labvec, ct_group, gene_names] = ...
    Cell_Type_Data_Extract_Tasic(classstruct,'VLMC',matdir);

save([matdir filesep 'Tasic_Inputs.mat'],'genevct','genevct_subt',...
    'classkey','classkey_subt','C_indivcells','ct_labvec','subt_labvec',...
    'ct_group','gene_names','GENGDmod','listBmap','nonzerovox',...
    'structIndex','structList','voxvgene');